# Generated by Django 4.0.4 on 2022-04-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField(verbose_name='Latitude (degrees)')),
                ('lon', models.FloatField(verbose_name='Longitude (degrees)')),
                ('alt', models.FloatField(verbose_name='Altitude (meters)')),
            ],
        ),
    ]
